// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv7IU6f1iyF7gDMYc9myqQR6uffwPYHCU',
    appId: '1:1053199746997:web:62c7cd618c71e9e0937bfc',
    messagingSenderId: '1053199746997',
    projectId: 'notes-app-997b5',
    authDomain: 'notes-app-997b5.firebaseapp.com',
    storageBucket: 'notes-app-997b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpU8qyf6jWpI0PDmVjazrIea8Gx3bIwEE',
    appId: '1:1053199746997:android:fd7f84821c7c645a937bfc',
    messagingSenderId: '1053199746997',
    projectId: 'notes-app-997b5',
    storageBucket: 'notes-app-997b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9udlO_Wywch7AO_AyjhWZWFtN9PbBaY',
    appId: '1:1053199746997:ios:38b8fe8d79e5f97a937bfc',
    messagingSenderId: '1053199746997',
    projectId: 'notes-app-997b5',
    storageBucket: 'notes-app-997b5.appspot.com',
    iosClientId: '1053199746997-qmqk0388qvg4t2a06ondbuutq1jgthnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9udlO_Wywch7AO_AyjhWZWFtN9PbBaY',
    appId: '1:1053199746997:ios:38b8fe8d79e5f97a937bfc',
    messagingSenderId: '1053199746997',
    projectId: 'notes-app-997b5',
    storageBucket: 'notes-app-997b5.appspot.com',
    iosClientId: '1053199746997-qmqk0388qvg4t2a06ondbuutq1jgthnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
